name: Step 2, TBD-step-2-name

# This step triggers after TBD-step-2-event-desc
# This step sets STEP to 3
# This step closes <details id=2> and opens <details id=3>

# This will run every time we push to the deploy-staging.yml file on the staging-workflow branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - staging-workflow
    paths:
      - .github/workflows/deploy-staging.yml

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  on_staging_workflow_update:
    name: On TBD-step-2-event

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 2 (see update-step.sh)
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ github.repository_owner != 'TBD-organization' }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Verify the learner added the environment variables
      - name: Verify environment variables set
        run: .github/script/check-file.sh
        env:
          FILE: .github/workflows/deploy-staging.yml
          SEARCH_LIST: 'DOCKER_IMAGE_NAME IMAGE_REGISTRY_URL AZURE_WEBAPP_NAME'

      # Verify the learner added the specific label triggers
      - name: Verify workflow
        run: .github/script/check-file.sh
        env:
          FILE: .github/workflows/deploy-staging.yml
          SEARCH: 'github.event.pull_request.labels'

      # Update README to close <details id=2>
      # and open <details id=3>
      # and set STEP to '3'
      - name: Update to step 3
        run: ./.github/script/update-step.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_STEP: 2
          TO_STEP: 3
          BRANCH_NAME: staging-workflow
